[project]
name = "hybridretrievalwebfallback"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.1.1",
    "debugpy>=1.8.17",
    "langchain-community>=0.3.31",
    "langchain-tavily>=0.2.12",
    "langchain[google-vertexai]>=0.3.27",
    "langgraph>=0.6.8",
    "langgraph-cli[inmem]>=0.4.3",
]

